package alpvax.waroflight.core;

import alpvax.waroflight.blocks.WOLBlocks;
import alpvax.waroflight.emotions.EnumEmotion;
import alpvax.waroflight.items.WOLItems;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;


@Mod(modid = WOLConstants.MOD_ID)
public class WarOfLightMod
{
	@Instance(WOLConstants.MOD_ID)
	public static WarOfLightMod instance;

	@Metadata(WOLConstants.MOD_ID)
	public static ModMetadata meta;

	public static CreativeTabs creativeTab = new CreativeTabs("warOfLight")
	{
		@Override
		@SideOnly(Side.CLIENT)
		public int getIconItemDamage()
		{
			return EnumEmotion.WILLPOWER.ordinal();//Green Lantern
		}

		@Override
		@SideOnly(Side.CLIENT)
		public Item getTabIconItem()
		{
			return Item.getItemFromBlock(WOLBlocks.lantern);
		}
	};

	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = WOLConstants.MOD_NAME;
		meta.version = WOLConstants.MOD_VERSION;
		/*TODO: Dependencies
		ArtifactVersion av = new DefaultArtifactVersion(PlayerPowersConstants.MOD_ID, true);//Unbounded
		meta.requiredMods.add(av);//Required
		meta.dependencies.add(av);//After
		 */
		meta.authorList.add("Alpvax");
		meta.credits = "Initial idea courtesy of Tallen121, based upon the DC Superhero Green Lantern comics";
		meta.autogenerated = false;

		new WOLBlocks();//Register Blocks
		new WOLItems();//Register Items

		MinecraftForge.EVENT_BUS.register(new WOLHooks());
	}
}
