package alpvax.wayoflight.core;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.versioning.ArtifactVersion;
import net.minecraftforge.fml.common.versioning.DefaultArtifactVersion;
import alpvax.playerpowers.api.PlayerPowersConstants;
import alpvax.wayoflight.blocks.WOLBlocks;
import alpvax.wayoflight.items.WOLItems;


@Mod(modid = WOLConstants.MOD_ID)
public class WayOfLightMod
{
	@Instance(WOLConstants.MOD_ID)
	public static WayOfLightMod instance;

	@Metadata(WOLConstants.MOD_ID)
	public static ModMetadata meta;

	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = WOLConstants.MOD_NAME;
		meta.version = WOLConstants.MOD_VERSION;
		ArtifactVersion av = new DefaultArtifactVersion(PlayerPowersConstants.MOD_ID, true);//Unbounded
		meta.requiredMods.add(av);//Required
		meta.dependencies.add(av);//After
		meta.authorList.add("Alpvax");
		meta.credits = "Initial idea courtesy of Tallen121, based upon the DC Superhero Green Lantern comics";
		meta.autogenerated = false;

		new WOLBlocks();//Register Blocks
		new WOLItems();//Register Items
	}
}
